name: CI -> Deploy to My website
on:
  push:
    branches: [ master, development ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Here is the deployment action
      - name: Upload from app via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          remote_dir: "./htdocs"